export default {
  carosoul1: "/images/carosoul1.png",
  carosoul2: "/images/carosoul2.png",
  carosoul3: "/images/carosoul3.png",
  loupe: "/images/loupe.png",
  truckBgWhite: "/images/truckBgWhite.png",
  mapImage: "/images/map2.png",
  portImage: "/images/portImage.png",
  sun: "/images/sun.png",
  moon: "/images/moon.png",
  image11: "/images/image1.png",
  image22: "/images/image2.png",
  image33: "/images/image3.png",
  image1: "/images/rail.jpg",
  image2: "/images/port.jpg",
  image3: "/images/empty.jpg",
  logo1: "/images/logo11.png",
  logo2: "/images/logo22.png",
  logo3: "/images/logo3.png",
  logo4: "/images/logo4.png",
  logo5: "/images/logo5.png",
  logo6: "/images/logo6.png",
  logo7: "/images/rail.jpg",
  pin: "/images/pin.png",
  search: "/images/search1.png",
  topBar: "/images/up-caret.png",
  leftBar: "/images/right-caret.png",
  downarrow: "/images/down-arrow218.png",
  background: "/images/shutterstock_585758060 (1).jpg",
  ogImage :"/images/logoOg.png"

};
