import Layout from "../components/layout";

export default function App() {
  return (
    <Layout title={"FR8 | Privacy"}>
      <div className="text-center">
        <img src="images/logo.png" />
      </div>
      <div className="policy_new" style={{backgroundColor:"#fff"}}>
        <div className="container">
          <div className="row">
            <h2>FR8 - PRIVACY POLICY</h2>
            <p>
              FR8 Media respects your privacy. FR8 Media and its affiliates
              (“FR8” or the “Company”) offer mapping, GPS navigation, community
              based services and Media services to users of www.FR8.ai (the
              “Website”) and/or users of FR8’s mobile applications (the
              “Application”) (collectively referred to as the “Services”). When
              you use our services, you’re trusting us with your information. We
              understand this is a big responsibility and work hard to protect
              your information and put you in control.
            </p>
            <p>
              This Privacy Policy is meant to help you understand what
              information we collect, why we collect it, and how you can update,
              manage, and delete your information. This Privacy Policy covers:
            </p>
            <p>
              This Privacy Policy is incorporated as part of the FR8 Terms of
              Use and FR8 Media Terms of Use (the “Terms of Use” or the
              “Terms”). Your use of the Services is subject to the Terms of Use,
              Copyright Policy and this Privacy Policy and indicates your
              consent to them.
            </p>
            <p>
              To use our Services you must be 16 years of age or older. If you
              are under 16, you may not download or use the Services.
            </p>
            <p>
              In this Privacy Policy, the term “personal information” means
              information which you provide to us which personally identifies
              you, such as your name, email address or billing information, and,
              in certain circumstances, your location and route information or
              other data which can be reasonably linked to such information by
              FR8.
            </p>
            <p>
              You can adjust your Privacy Settings in the FR8 app and choose
              which personal information we may collect about you and how your
              information is used.
            </p>
            <h2>Contact FR8 - Privacy concerns reports</h2>
            <p>
              If you have any questions about this Privacy Policy, or if you
              believe that your privacy has been compromised in the course of
              using the Services, please contact FR8 at: support@fr8.ai. You may
              send FR8 other requests, responses, questions and complaints by
              email at: support@fr8.ai.
            </p>
            <h2>{"User Accounts & Accessing the Services"}</h2>
            <p>
              Please note that when you use our Services , FR8 will set up an
              account (the “Account” or “FR8 Account”). FR8 will collect and use
              your information, including meta-data (as described below), in
              accordance with this Privacy Policy. This is the case whether or
              not you choose to actively register your Account, for example, by
              adding your email address or logging with your FR8 Media Account.
              FR8 may allow you to use the Services whether or not you choose to
              register your Account. If you choose to use the FR8 Services
              without registering your account you may do so by skipping the
              registration process. If you do so:
            </p>
            <ul>
              <li>
                FR8 will still link all of your information with the
                non-registered Account and a unique identifier generated by FR8
                in accordance with this Privacy Policy. This helps us do things
                like find you the best route.
              </li>
              <li>
                FR8 may allow you to connect your non-registered account with
                other devices and browsers (for example by using a QR code) and,
                if you choose to do so, information collected from these devices
                and browsers will be linked to your non-registered account.
              </li>
              <li>
                With the exception described in the bullet below, and as
                explained in the section “Visibility” below, your Account and
                the information associated with your Account (including your
                unique identifier) will be visible only to FR8; and
              </li>
              <li>
                When using the Services, your approximate location and other
                information you may choose to contribute will be visible to
                other users associated with the general username “FR8r”.
              </li>
              <li>
                Note that in order to access certain features of the Services
                (for example map editing, FR8 Media, ranking, moods) you will
                need to register your account.
              </li>
            </ul>

            <h2>If you do register your Account:</h2>
            <ul>
              <li>
                FR8 will link all of your information with your registered
                Account. This includes information received from all devices and
                browsers which you have chosen to sign in ;
              </li>
              <li>
                With the exception described in the bullet below and as
                explained in the section “Visibility” below, your Account and
                information associated with your Account will be visible only to
                FR8; and
              </li>
              <li>
                When using the Services, your approximate location and other
                information you may choose to contribute will be visible to
                other users associated with this Account.
              </li>
              <li>
                FR8 may also establish and require from time to time additional
                or different means of identification and authentication for
                logging in and accessing the Services or for accessing certain
                features or designated sections of the Services.
              </li>
              <li>
                Your login details are your responsibility. You are fully
                accountable for any use or misuse of your Account and personal
                details as a result of conveying your login details to someone
                else. You must maintain your login details in absolute
                confidentiality and avoid disclosing them to others. If you set
                a password, make sure that you change your password frequently
                and at least once every six months.
              </li>
            </ul>
            <h2>Information that is being collected</h2>
            <h4>
              We want you to understand the types of information we collect as
              you use our services
            </h4>
            <p>
              FR8 collects information to provide better services to all its
              users - from figuring out stuff like what’s the best route, to
              more complex things like monitoring traffic so you know when to
              leave, and showing you relevant ads while using FR8. The
              information FR8 collects, and how that information is used,
              depends on how you choose to use our services and how you manage
              your privacy controls.
            </p>
            <h3>Information you create or provide to us:</h3>
            <p>
              <strong>Account Information:</strong> information required when
              setting up an Account, such as your name, email address or
              information required to create a Media profile (if you choose to
              do so). Bear in mind that false, incorrect, or out-dated
              information may impair FR8’s ability to provide you with the
              Services and to contact you when necessary. FR8 will explicitly
              indicate the fields for mandatory completion. If you do not enter
              the requisite data in these fields, you may not be able to
              register your Account or to be provided with certain features,
              such as FR8 Media (but you may still use our Services as explained
              in the above section “User Accounts & Accessing the Services”);
              and/or
            </p>
            <p>
              <strong> Information that you choose to share with FR8:</strong>{" "}
              information that you choose to share with FR8, including a
              username you have chosen, reports associated with your username,
              phone number, “home” or “work”, other “favorites”, car’s details,
              destinations you may travel to, search queries, calendar
              information (if you choose to activate and use certain Service
              features like time to leave reminders) and files you have uploaded
              to the service, including voice and audio files, if applicable.
              You can also choose to add payment information to your Account, if
              applicable, specifically for paid services (such as FR8 Media).
              Even if you aren’t registered to a FR8 Account, you might choose
              to provide us with information.
            </p>
            <p>
              <strong>
                Communication which you choose to conduct through the FR8
                Services:
              </strong>{" "}
              if you choose to use FR8 to communicate with other FR8 users or
              third parties through the FR8 Services, such as chat messages or
              sending pinned locations on the FR8 platform. We may also collect
              information when you exchange communication with FR8, for example,
              if you submit a request, contact FR8’s support team, or report a
              violation to the abuse team.
            </p>
            <p>
              <strong>
                Information from your social networks which you choose to
                connect to your FR8 Account:
              </strong>{" "}
              you may choose to connect your FR8 Account to your social network
              account(s). If you choose to do so, you may choose to share with
              FR8 and/or other users information from your social network
              accounts, such as your Facebook profile photo or other personal
              information shared by you. For more information see Integration
              with social networks, below.
            </p>
            <p>
              <strong> “Find friends feature”:</strong> if you use the “find
              friends” feature, FR8 will collect:
            </p>
            <p>
              o Periodically, FR8 will collect all of the phone numbers which
              are stored on your device’s phone contacts book. With regards to
              the “find friends” feature we only collect numbers in a form which
              is anonymous to FR8; This information will be used to help us find
              and create a list of other FR8 users who you may know and with
              whom you may wish to connect. Note that we will not collect names,
              addresses or other information from your device’s phone contacts
              book, however some of this information may be saved locally on
              your device and may be used within searches for your friend’s name
              or address within the Services. and/or
            </p>
            <p>
              o Your phone number. Your phone number will be used to verify your
              account and as part of the “find friends” feature , if applicable,
              to help find and create a list of other FR8 users who you may know
              and with whom you may wish to connect.
            </p>
            <p>
              You may also provide additional information that will be used to
              personalize the Services and enhance your experience with the
              Services. For example, if you provide us with your “home” and
              “work” information, we may provide you with what we think is the
              preferred route between those locations.
            </p>
            <h2>Information we collect as you use our services</h2>
            <p>
              We collect information about your activity in the Services, which
              we use to provide you with the Services of FR8, including features
              which are meant to personalize your experience. This includes
              things like finding you the preferred route and proposing
              favorites or destinations commonly traveled by you to streamline
              your search and travel and, if you use FR8 Media - to match you
              with other drivers or riders. The activity information we collect
              may include:
            </p>
            <ul>
              <li>
                Detailed location, travel and route information. Location and
                route information is collected for example in the form of GPS
                signals (combined with a time-stamp), IP address and other
                information from sensors and receivers on or around your
                device,on which the Application is installed and activated. This
                location and route information is saved to a route history of
                all of the journeys you have made while using the Application.
                The types of location data we collect depends in part on your
                device and account settings. For example, depending on your
                selected device settings and/or your account settings we may
                collect information about your location and travel (or lack
                thereof) also while you are not using the app, in order to be
                able to tell you when to leave for planned drives, notify you
                about bad traffic in your area, provide you parking assistance,
                analyze how effective our ads are and more;
              </li>
              <li>Terms or venues you searched;</li>
              <li>Your views and interactions with content and ads;</li>
              <li>
                Your voice and audio information when you use voice and audio
                features;
              </li>
              <li>
                Communication or other content you chose to share with any third
                party, including FR8 users through the Services;
              </li>
              <li>
                Your activity on third-party sites and apps that you chose to
                link to your FR8 account or that you interact with through the
                Service.
              </li>
              <li>
                {" "}
                Your activity as a FR8 Media’s rider or driver, such as users
                you interacted with and rating that you have received from other
                users.
              </li>
            </ul>
            <h2>
              Meta-data (information about your device, browser and app use):
            </h2>
            <h3>
              FR8 collects information about the use of the Services and
              information from the device you have FR8 installed on or the
              browser from which you use our Services. For example:
            </h3>
            <ul>
              <li>
                FR8 may collect and record how often you use our Services and
                for how long, your device type, unique identifiers, operating
                system type & version, battery usage, the third party web pages
                or applications you visit or use or interact with via the
                Application, information that you viewed on our Services,
                advertisements that are shown to you or that you view or click
                on, the fact that you used the Services to communicate with
                other users and the fact that you used third parties
                application/services via FR8 to communicate with third parties,
                and the duration of such communications, the Internet Protocol
                (IP) address and the name of the domain that serves you to
                access the Services, and the geographic location of the device
                that you are using to log in and use FR8 on.
              </li>
              <li>
                FR8 may also collect information about apps installed on your
                device that FR8 can link with - such as third party music or
                media audio service apps (e.g. FR8 Media).
              </li>
              <li>
                We also collect information about the interaction of your
                devices with our Services, including, crash reports, system
                activity, and the date, time, and referrer URL of your request.
              </li>
              <h2>Information we collect about you from our partners</h2>
              <p>
                We work with ad partners, including advertisers on our platform
                and entities that belong to the FR8 Media group of companies, in
                order to show you more relevant and useful ads based on your FR8
                activity and information associated with your device’s
                identifier (i.e, Advertising identifiers or similar
                technologies) shared with us by our ad partners. Your device’s
                identifier can be managed in your device’s settings (for more
                information: see here and here).
              </p>
              <p>
                You can decide whether we’ll show you personalized ads or not
                through your in-app
                <strong>
                  {" "}
                  {"Privacy Settings–>Ads personalization."}
                </strong>{" "}
                Note: turning Ads personalization off does not turn off ads -
                only their personalization. For more information see section
                titled ‘Advertising campaigns’ under this Privacy Policy.
              </p>
              <p>
                We may also receive aggregated, non-personally identifiable
                information and analysis from third parties measurement services
                which help us understand how our users interact with our ads. We
                may also receive information from third party services about how
                FR8’s own marketing efforts performed on third party sites or
                platforms.
              </p>
              <p>
                We use various technologies to collect and store information,
                including, cookies, Advertising ID available on Android mobile
                devices or similar technologies, local storage, browser web
                storage, application data caches, databases, and server logs.
              </p>
              <h2>Why FR8 collects data</h2>
              <h4>
                FR8 may use information collected from or provided by you for
                the following purposes:
              </h4>
              <h3>Provide our services</h3>
              <ul>
                <li>
                  {" "}
                  We use your information to deliver our services. For example:
                  Use your location and route information and/or search query
                  history to provide navigation services, best route choices,
                  traffic alerts and to provide information about sites, shops
                  and other places and attractions in your close vicinity; and
                </li>
                <li>
                  {" "}
                  (If you have opted in to the “find friends” feature), use your
                  phone number and the phone numbers which are stored in your
                  device’s phone book to find and create a list of other FR8
                  users who you may know and with whom you may wish to connect.
                </li>
                <li>
                  To provide advertising services, including personalized ads,
                  in accordance with the section titled ‘Advertising campaigns’
                  under this Privacy Policy.
                </li>
                <li>
                  To share your submissions with other users of the Services and
                  to facilitate communication between you, FR8 and other users.
                </li>
                <li>
                  If you joined FR8 Media, use your information, such as home,
                  work and schedule, to find you potential discounts during your
                  trips;
                </li>
              </ul>
              <h2>Maintain & improve our services</h2>
              <ul>
                <li>
                  {" "}
                  We also use your information to ensure our services are
                  working as intended, such as tracking outages or
                  troubleshooting issues you report to us. And we use your
                  information to improve the service or to develop new features
                  or services. For example, FR8 may use your route information
                  to improve the accuracy of its mapping and navigation data.
                </li>
              </ul>
              <h2>Provide personalized services, including content and ads</h2>
              <ul>
                <li>
                  We use the information we collect to operate the Services and
                  to customize your experience with the Services. For example,
                  FR8 may use your “home” and “work” and other “favorites”
                  information (if you choose to provide such information) or
                  route history to offer routes based on how you’ve chosen to
                  travel between favorite destinations in the past. Based on
                  your past activity on the Services we may also suggest to you
                  drive predictions and common destinations where you use the
                  app to navigate to and personalize your ETA.
                </li>
                <li>
                  {" "}
                  If you have opted in to use FR8 Media, we use your information
                  to match you with riders and/or drivers to help you find a
                  ride.
                </li>
                <li>
                  We may also use the information to provide you with support
                  and handle requests and complaints.
                </li>
                <li>
                  {" "}
                  Depending on your settings, we may also show you personalized
                  ads based on your interests and past activity. For more
                  information see section titled ‘Advertising campaigns’ under
                  this Privacy Policy.
                </li>
              </ul>
              <h2>Measure performance</h2>
              <p>
                {" "}
                We use data for analytics and measurement to understand how our
                services are used. For example, we analyze data about your usage
                of the Services to do things like optimize product design. We
                also use the data we collected about the ads you view or
                interact with (e.g. click on) to help advertisers understand the
                performance of their ad campaigns and to provide them with
                aggregated reports. We may also use data to measure the
                usability and effectiveness of FR8’s own marketing efforts on
                third party sites or platforms.
              </p>
              <h2>Communicate with you</h2>
              <ul>
                <li>
                  {" "}
                  We also use your information to send you updates, notices,
                  announcements, users’ requests and additional information
                  related to the Services (including through push notifications,
                  email address and SMS);
                </li>
                <li>
                  {" "}
                  We may also use your information to conduct surveys and
                  questionnaires; And if you contact FR8 we may keep a record of
                  your request in order to help solve any issues you might be
                  facing.
                </li>
                <li>
                  {" "}
                  • Subject to your prior indication of consent (to the extent
                  required under applicable law), we may also use the email
                  address that you provided to send you promotional and/or
                  marketing materials. At any time you may choose not to receive
                  such materials by clicking on the “Unsubscribe” link in the
                  email messages that we may send to you. In any case, FR8 will
                  not share your contact details with any advertiser, unless
                  explicitly permitted or required by law.{" "}
                </li>
              </ul>
              <h2>
                To protect FR8, our users, the public and for Legal reasons
              </h2>
              <p>
                We may also use and process your information and content, using
                different technologies to the following purposes:
              </p>
              <ul>
                <li>To enforce the Terms of Use or Privacy Policy;</li>
                <li>To contact you when FR8 believes it to be necessary;</li>
                <li>
                  {" "}
                  To comply with any applicable law and assist law enforcement
                  agencies under any applicable law, when FR8 has a good faith
                  belief that FR8’s cooperation with the law enforcement
                  agencies is legally mandated or meets the applicable legal
                  standards and procedures;
                </li>
                <li>
                  To detect abuse and illegal activity; to detect and prevent
                  fraud, misappropriation, infringements, identity theft and
                  other illegal activities and misuse of the Services;
                </li>
                <li>To handle breakdowns and malfunctions;</li>
                <li>
                  {" "}
                  To take any action in any case of dispute, or legal proceeding
                  of any kind between you and the Services, or between you and
                  other users or third parties with respect to, or in relation
                  with the Services;
                </li>
                <li>
                  For purposes provided under this Privacy Policy and Terms of
                  Use;
                </li>
                <li>
                  To help improve the safety and reliability of our Services.
                  This includes detecting, preventing, and responding to
                  security risks, and technical issues that could harm FR8, our
                  users, or the public;
                </li>
                <li>
                  {" "}
                  To create aggregated and/or anonymous data (where such data
                  does not enable the identification of a specific user). See
                  “How does FR8 use aggregated information”, below;
                </li>
              </ul>
              <h3>
                We’ll ask for your consent before using your information for a
                purpose that isn’t covered in this Privacy Policy.
              </h3>
              <h2>Sharing your information</h2>
              <h3>Personal information that you share</h3>
              <p>
                The Services are based on a community of users publicly sharing
                information with FR8 and with other members of that community.
              </p>
              <p>
                In particular, users may choose to share personal information
                such as name, age, gender, picture, their location information,
                reports and other files. This information may be shared either
                directly to the Services and to all users, such as in the case
                of traffic reports, or just to your friends on FR8. This
                information may also be shared via third party services (such as
                social networks) which interact with the Services upon such
                users’ choice. For more information about your Media profile (if
                you choose to set one), see section titled FR8 Media Profile
                below.
              </p>
              <p>
                <strong>
                  You can decide whether or not to upload content to the
                  Services. However any content that you choose to share and
                  submit for posting is neither private nor confidential and you
                  should expect that it may be made public and known to others.
                </strong>{" "}
                Information you choose to upload will be posted along with your
                user name and other information including personal information
                you attached to your publicly available user profile. For
                example, your reports (map and road updates, traffic congestion
                updates, road accidents, etc.) will be posted on the FR8 map
                along with your username. You should note that certain road
                incidents you report may include your driving path within the
                vicinity of those incidents. Therefore, you must exercise
                caution and common sense when submitting information. At the
                very least you should demonstrate the same degree of caution as
                when publishing personal information by means other than the
                Internet and cellular services.
              </p>
              <p>
                In any event (but except as detailed below with respect to
                information shared from your social network accounts according
                to your privacy settings for such social network accounts), your
                email address will not be visible to others through any reports
                or user posts that you share or upload.
              </p>
              <p>
                if you choose to either record your own voice onto the Service,
                or to use the voice command features, FR8 will collect the voice
                information related to such use, including voice files. If,
                after recording your own voice, you chose to share your voice
                recordings, other FR8 users and other people will be able to
                download and use your voice recordings. Once downloaded, FR8 may
                not have any control over the voice files, so you should only
                share content that you are comfortable being made public.
              </p>
              <p>
                We, at FR8, take great measures to provide you with the best
                experience you can have while using the Services. However, FR8
                has no control over the conduct of any user and disclaims all
                liability in this regard. Users are advised to carefully and
                thoroughly consider whether or not to make public or available
                any information and carefully examine all necessary details
                related to any communication with other users prior to any
                engagement or communication being made.
              </p>
              <p>
                Participating in any user’s activities as a result, directly or
                indirectly, from using FR8, is entirely at your own risk. FR8 is
                not a party to any agreement entered into between the users in
                any circumstances. The user has the sole and ultimate
                responsibility regarding compliance with all laws, regulations
                or any other duty. We do not accept any liability for any loss,
                damage, cost or expense that you may suffer or incur as a result
                of or in connection with your participation in any activity or
                event initiated, held or conducted by a user or a third party
                nor in connection to any agreement between the users or third
                parties, including any activity or event related in any way,
                directly or indirectly, the Services or the use thereof.
              </p>
              <h2>When FR8 shares your information</h2>
              <h3>
                FR8 does not sell, rent or lease your personal information to
                third parties.
              </h3>
              <h3>
                FR8 will not share your personal information with others,
                without your permission, except for the following purposes and
                to the extent necessary in FR8’s good-faith discretion:
              </h3>
              <ul>
                <li>
                  {" "}
                  As necessary for the facilitation and operation of the
                  Services. For example, making public road incidents you report
                  and which are associated with your username and your location;
                </li>
                <li>
                  If FR8 reasonably believes that you have breached the Terms of
                  Use or is investigating potential breach of the Terms of Use,
                  or believes that you abused your rights to use the Services,
                  or performed any act or omission that FR8 reasonably believes
                  to be violating any applicable law, rules, or regulations. FR8
                  may share your information in these cases, with law
                  enforcement agencies and other competent authorities and with
                  any third party as may be required to handle any result of
                  your wrongdoing;
                </li>
                <li>
                  If FR8 is required, or reasonably believes that it is required
                  by law to share or disclose your information;
                </li>
                <li>
                  In any case of dispute, or legal proceeding of any kind
                  between you and FR8, or between you and other users with
                  respect to, or in relation with the Services;
                </li>
                <li>
                  In any case where FR8 reasonably believes that sharing
                  information is necessary to protect against harm to the
                  rights, property or safety of FR8, our users, or the public as
                  required or permitted by law, including to prevent imminent
                  physical damage or damage to property;
                </li>
                <li>
                  To detect, prevent, or otherwise address fraud, security, or
                  technical issues;
                </li>
                <li>
                  If FR8 organizes the operation of the Services within a
                  different framework, or through another legal structure or
                  entity, or if FR8 is acquired by, or merged into or with
                  another entity, or if FR8 enters bankruptcy, provided however,
                  that those entities agree to be bound by the provisions of
                  this Privacy Policy, with respective changes taken into
                  consideration;
                </li>
                <li>
                  {" "}
                  To collect, store, hold and manage your personal information
                  through cloud based or hosting services or a third party or a
                  party affiliated or connected to FR8, as reasonable for
                  business purposes, which may be located in the European Union
                  and the U.S.A., potentially countries outside of your
                  jurisdiction;
                </li>
                <li>
                  FR8 may also share personal information with companies or
                  organizations connected or affiliated with FR8, such as
                  subsidiaries, sister-companies and parent companies (i.e.
                  entities that belong to the FR8 Media group of companies);
                </li>
                <li>
                  We work with other FR8 Media’s services (such as FR8 Media
                  Display and Video 360) for advertising and ad measurement
                  purposes. In order to help advertisers decide what ads to show
                  on FR8, FR8 Media, and websites & apps that partner with FR8
                  Media, we may share information with these services, such as a
                  unique identifier for advertising (i.e, Advertising ID
                  available on Android mobile devices or similar technologies).
                  You can learn more about how FR8 Media uses information from
                  sites or apps that use its services and how you can control
                  that in this page. For more information see section titled
                  ‘Advertising campaigns’ under this Privacy Policy.
                </li>
                <li>
                  We also work with selected advertising and measurement
                  services which help us understand how our users interact with
                  ads served in our platform and in order to provide marketing,
                  advertising and measurement services for FR8 with respect to
                  FR8’s own marketing efforts, by using and sharing devices’
                  identifiers (i.e, Advertising ID, cookies or similar
                  technologies).
                </li>
                <li>
                  {" "}
                  Personal information may also be shared with FR8’s trusted
                  partners and service providers to process it for us, based on
                  our instructions and in compliance with this policy and any
                  other appropriate confidentiality and security measures. For
                  example, we use service providers to help us with customer
                  services.
                </li>
              </ul>
              <p>
                We may share information which does not personally identify you
                with third party transportation services. For example, to allow
                you to find a Media rider on third party transportation
                services, such as Moovit, we may share a temporary unique
                identifier along with pick-up and drop-off points that are
                generated based on proximity to your intended travel itinerary,
                with those third party transportation services. You can review
                the list of the relevant third party transportation services to
                your area and change your preferences at any time via the in-app
                settings.
              </p>
              <p>
                FR8 Media partners with employers, organizations and
                governmental entities (“FR8 Media Partners”) in order to
                encourage the use of Mediaing. If you have joined a Media group
                which is promoted by a partner or any other third party, your
                Media profile (or other information you have chosen to share)
                may be visible to other members of the group, including
                representatives of the partner or third party who may also be
                part of the group.
              </p>
              <h2>Visibility</h2>
              <p>
                Please note that your username and some other information will
                be visible to others. Note that your username will be included
                along with any information you submit for posting (such as
                traffic reports or chat messages). It will therefore be visible
                to others. Also - your friends on FR8 will see your name &
                profile photo and any other information you chose to share with
                them.
              </p>
              <p>
                If you prefer to remain invisible on the FR8 map, you can set
                the FR8 Application not to show your location on the map. To do
                so you should go to the Privacy Settings and adjust accordingly
                by switching on to Invisible Mode. If on, some features may not
                be available. If you make this choice, while you will be
                ‘invisible’ on the map to other users, your location and route
                information will continue to be collected by FR8 for the
                purposes listed in this Privacy Policy and your Media profile
                (if you choose to set one) may be visible to other FR8’s users.
              </p>
              <h2>FR8 Media Profile</h2>
              <p>
                FR8 Media is uniquely designed to help drivers and riders find a
                mutual ride that fits them. If you have opted-in to use the FR8
                Media feature, you will be required to create a unique profile.
              </p>
              <p>
                Your FR8 Media profile includes your name, photo, number of
                completed rides and Mediaed km, the date you joined the
                services, information that you have chosen to share from your
                social account, your Media rating and endorsements you have
                received, and any other information you shared about yourself
                (for example your car details or any other information as part
                of “My Preferences” settings). You can edit some of this
                information through the in-app settings or through your social
                account (in case you have chosen to share the information from
                your social account).
              </p>
              <p>
                A complete Media profile is important so that riders or drivers
                can learn more about you, and vice versa. Your profile is
                therefore public to other FR8 users and may be shared through
                our services. If you have joined the Media Groups feature, your
                Media profile will be visible to other group members, including
                your co-workers or employer in case of work related groups.
              </p>
              <p>
                If you choose to verify your work or university’s email address,
                your work or university will be listed publicly on your profile
                as well (but your email address will stay private).
              </p>
              <p>
                Note: your home and work addresses are not listed publicly on
                your profile, but rather only be saved on your FR8 account.
                However, in certain circumstances, your pickup/drop-off spots
                may be your home or work address if for example you share a
                similar route with your driver or rider.
              </p>
              <h2>Integration with social networks</h2>
              <p>
                You may choose to share information between your FR8 account and
                your social network account (such as Facebook). Through this
                option, you may choose to have personal information and other
                content about you available from social networks, transmitted
                and shared through the Services. Similarly, you may choose to
                have personal information and other content about you available
                from FR8, including your location and route information,
                transmitted to and shared through your social network account.
              </p>
              <p>
                By setting your FR8 Account to integrate with social networks,
                including by signing onto FR8 by using your social network
                account, you agree to share information (including personal
                information) between FR8 and such social networks, for the
                purposes provided under this Privacy Policy.
              </p>
              <p>
                The social network’s use of information made available by FR8 is
                governed by that social network’s privacy policy and controlled
                by the social network, not by this Privacy Policy or FR8.
              </p>
              <p>
                When you connect to the social network account through the
                Services for the first time or otherwise make the Services
                interact with your social network account, you will be asked by
                the social network to permit the social network to share your
                personal information stored on such social network with FR8. We
                collect your information from your social network account only
                in accordance with the permissions granted by you (such as your
                name, email address, list of friends, profile picture and other
                information available via the applicable social network).
              </p>
              <p>
                You understand and agree that the Services may access, make
                available and store such information so that it is available on
                and through your FR8 Account, until your FR8 Account is deleted.
              </p>
              <p>
                Please note that certain information which you have defined as
                private on your third party social network accounts may become
                public to other FR8 Users through the Services once you have
                allowed the social network to share such information with FR8
                (for example through your Media Profile).
              </p>
              <h2>Integration with other third party services</h2>
              <p>
                FR8 may offer you the option to link FR8 to third party services
                that may be useful to you (like, FR8 Media). Where FR8 detects
                an integration may be available (either because a third party
                service attempts to link to FR8, or FR8 detects an installed
                service on the device which has an integration option, or you
                request a particular integration), FR8 will ask for confirmation
                to connect the accounts. If you choose to connect the accounts,
                FR8 will ask for your permission to share data with the third
                party service. You should only agree to connect accounts if you
                are comfortable with the third party service receiving the data
                set out at the time of connecting the accounts and FR8 is not
                responsible for the third party service’s use of data. You can
                disconnect FR8 and the third party service at any time and FR8
                will cease sharing data with that service from the point of
                disconnection onwards.
              </p>
              <h2>Controlling your personal information</h2>
              <p>
                You can always review and update certain information by visiting
                your Account & Login settings (such as your phone, name, photo
                and more) or the in-app left menu (to update your home, work and
                favorites). If you joined FR8 Media, you can review and update
                your information (including this available on your FR8 Media
                profile) through the FR8 Media in-app settings.
              </p>
              <p>
                You can log on to the FR8 website to view your route history by
                going to “Edit the Map”/ “Drives” function on the FR8 website.
                Note that in order to access certain information you will need
                to register your Account. Your location and route history is
                associated with your Account.
              </p>
              <p>
                If you find that the information associated with your Account is
                not accurate, complete or updated, then you should make all
                necessary changes to correct it. Please keep in mind that false,
                incorrect, or outdated information may prevent you from setting
                up an Account and impair the ability to provide you with
                Services.
              </p>
              <h2>Privacy controls</h2>
              <p>
                Your in-app Privacy Settings provide you with quick access to
                settings and tools that let you safeguard your data and decide
                how your information can make FR8 services work better for you.
                For example, you can control your visibility on the map and
                manage your preferences about the ads shown to you on FR8. If
                you joined FR8 Media, you can access more controls through your
                Media activity and other in-app settings.
              </p>
              <p>
                There are other ways to control the information FR8 collects
                whether or not you’re signed in to a FR8 Account, including
                device-level settings: your device may have controls that
                determine what information we collect. For example, you can
                modify location settings on your device.
              </p>
              <h2>Deleting your information</h2>
              <p>
                If you would like us to delete your Account, please use the
                “Delete Account” function available under the in-app Privacy
                Setting and on the FR8 website. On receiving such a request, FR8
                will use reasonable efforts to delete such information, however
                please note that information may not be deleted immediately from
                our back-up systems. We aim to initiate the deletion process
                immediately after your request. Once we receive your request,
                your data will no longer be used to personalize your FR8
                experience. We then begin a process designed to safely and
                completely delete the data from our storage systems. This
                process generally takes around 2 months from the time of
                deletion. As with any deletion process, things like routine
                maintenance, unexpected outages, bugs, or failures in our
                protocols may cause delays in the processes and time frames
                defined in this policy. We maintain systems designed to detect
                and remediate such issues.
              </p>
              <h2>How FR8 retains data we collect</h2>
              <h3>
                Some data you can delete whenever you like, some data is deleted
                automatically, and some data we retain for longer periods of
                time when necessary. This section describes why we hold onto
                different types of data for different periods of time.
              </h3>
              <ul>
                <li>
                  Information retained until you remove it - such as your “Home,
                  “work”, favorites, email address and other account related
                  information. We’ll keep this data in your FR8 Account until
                  you choose to remove it and/or update it.
                </li>
                <li>
                  Data that expires after a specific period of time - in some
                  cases, you don’t need to actively delete your information as
                  we set retention timeframes based on the reason for the data’s
                  collection. For example, if you choose to connect your
                  calendar to your FR8 Account, we extract your calendar events
                  for several days in advance and delete them after their
                  occurrence. We may also take steps to anonymize certain data
                  within set timeperiods.
                </li>
                <li>
                  Information retained until your FR8 Account is deleted - we
                  may keep some data for the life of your FR8 Account if it’s
                  useful for helping us understand how users interact with our
                  features and how we can improve our services. For example, if
                  you made an incident report, we will keep information about
                  how many reports you have submitted, even after the event is
                  removed. When you delete your FR8 Account, the information
                  about how many reports you have submitted is also removed.
                </li>
                <li>
                  Information retained for extended time periods for limited
                  purposes - sometimes business and legal requirements oblige us
                  to retain certain information, for specific purposes, for an
                  extended period of time. For example, when FR8 processes a
                  payment for you, we’ll retain this data for longer periods of
                  time as required for tax or accounting purposes. Reasons we
                  might retain some data for extended periods of time include:
                </li>
              </ul>
              <ul className="line_item">
                <li>o Security, fraud & abuse prevention</li>
                <li>o Financial record-keeping</li>
                <li>o Complying with legal or regulatory requirements</li>
                <li>o Ensuring the continuity of our services</li>
                <li>o Direct communications with FR8</li>
              </ul>
              <h2>How does FR8 use aggregated information?</h2>
              <p>
                FR8 may use anonymous, statistical or aggregated information
                (including anonymous location information), in a form that does
                not enable the identification of a specific user, to properly
                operate the Services, to improve the quality of the Services, to
                enhance your experience, to create new services and features,
                including customized services, to change or cancel existing
                content or service, and for further internal, commercial and
                statistical purposes (including advertising).
              </p>
              <p>
                FR8 may also use anonymous, statistical or aggregated
                information collected on the Services, in a form that does not
                enable the identification of a specific user, by posting,
                disseminating, transmitting or otherwise communicating or making
                available such information to users of the Services, to the
                Services’ providers, partners and any other third party. For
                example, GPS information that we receive from your mobile device
                may be provided to map editors in an aggregated and/or anonymous
                form to help improve the map and solve map problems, traffic
                data may be provided to cities, aggregated use of FR8 Media may
                be provided to Media Partners and aggregated ads analysis may be
                provided to advertisers.
              </p>
              <h2>Cookies</h2>
              <p>
                FR8 may use cookies and similar technologies on the Services.
                Cookies are packets of information sent by the Website’s servers
                to your web browser and then sent back by the browser each time
                it accesses the Website’s servers.
              </p>
              <p>
                FR8 may use cookies for various purposes, such as to save you
                the need to re-enter your username and password each time you
                log in, to facilitate the use of the Website, to collect
                statistical information, to verify information, and to customize
                the Website to your personal preferences and for information
                security purposes.
              </p>
              <p>
                Some of the cookies may expire when the session ends and you
                exit your browser. Other cookies are saved on your computer’s
                hard drive. If you wish to block the Website’s cookies, then
                please use the help button in your browser and follow the
                necessary instructions. However, bear in mind that disabling
                cookies may complicate or even prevent your use of the Website,
                or certain features thereof.
              </p>
              <p>For more information visit our Cookie Policy.</p>

              <h2>Advertising campaigns</h2>
              <p>FR8 allows advertisers to run ad campaigns on the Services.</p>
              <p>
                The information and advertisements that you see when accessing
                the Services may be targeted on the basis of your current FR8
                activity, such as your current location, your destination or
                contextual information based on your current drive session. For
                example: if you search for “gas station” you may see an ad for a
                local gas station.
              </p>
              <p>
                Depending on your settings, you may also see ads personalized to
                you based on:
              </p>
              <ul>
                <li>
                  Information we received from you (for example, your saved
                  “Home” & “Work” addresses)
                </li>
                <li>
                  Past activity and search query history (for example, drives
                  that appear in your drive list)
                </li>
                <li>
                  Information from our ad partners, including entities that
                  belong to the FR8 Media group of companies and other trusted
                  ad partners.
                </li>
              </ul>
              <h3>
                You can decide whether we’ll show you personalized ads or not
                through your in-app
                <strong>
                  {" "}
                  {"Privacy Settings–>Ads personalization."}
                </strong>{" "}
                Note: turning Ads personalization off does not turn off ads -
                only their personalization.
              </h3>
              <h4>Please note:</h4>
              <ul>
                <li>
                  {" "}
                  We don’t knowingly collect nor do we show you personalized ads
                  based on sensitive categories, such as race, religion, sexual
                  orientation, or health.
                </li>
                <li>
                  We don’t share information that personally identifies you with
                  advertisers, such as your name or email, unless you ask us to.
                  For example, if you see an ad for a nearby flower shop and
                  select the “tap to call” button, we’ll connect your call and
                  share your phone number with the flower shop.
                </li>
                <li>
                  As described under “When FR8 shares your information” section
                  above, we work with other FR8 Media’s services (such as FR8
                  Media Bid Manager) for advertising and ad measurement
                  purposes. In order to help advertisers decide what ads to show
                  on FR8, FR8 Media, and websites & apps that partner with FR8
                  Media, FR8 may share information with these services such as a
                  unique identifier for advertising (Advertising ID available on
                  Android mobile devices or similar technologies). You can learn
                  more about how FR8 Media uses information from sites or apps
                  that use its services and how you can control that in this
                  page.
                </li>
                <li>
                  The Ads personalization control described above apply to
                  personalized ads served by FR8 on the FR8 platform and they do
                  not apply to ads served on third parties platforms, including
                  on FR8’s behalf.
                </li>
                <li>
                  When you visit a third party website from the Application,
                  such third party may use cookies on your computer. The third
                  party’s use of cookies is subject to their own privacy
                  policies and not to this Privacy Policy. If you wish to study
                  the privacy policies of those third parties you should visit
                  their services, or contact them directly.
                </li>
              </ul>
              <p>
                The Services includes an internal messaging system which
                provides you the ability to send and receive messages to and
                from other users, and to receive marketing messages from us. You
                hereby agree that we may use the internal messaging system for
                the purpose of informing you regarding products or services,
                which may interest you.
              </p>
              <p>
                Please note however that other FR8 users are not allowed to use
                your contact details or our internal messaging account for
                commercial advertising purposes. If you have encountered any
                user generated advertising material, please inform us through
                the channels listed on the “About” menu in the Software or
                through the “Contact Us” page on the Site link here.
              </p>
              <p>
                It is clarified that we are not responsible for the content of
                said advertisements and the products delivered or services
                rendered thereby by third parties and you irrevocably and
                unconditionally agree that we shall not be held responsible or
                liable for any loss, damage, cost or expense that you may suffer
                or incur as a result or in connection thereof.
              </p>
              <h2>Information security</h2>
              <p>
                FR8 considers information security to be a top priority. FR8
                services are built with strong security features that
                continuously protect your information. FR8 implements systems,
                applications and procedures to secure your personal information,
                to minimize the risk of theft, damage, loss of information, or
                unauthorized access or use of information. For example, we
                review our information collection, storage, and processing
                practices, including physical security measures, to prevent
                unauthorized access to our systems. In addition, we restrict
                access to personal information to FR8 employees, contractors,
                and agents who need that information in order to process it.
                Anyone with this access is subject to strict contractual
                confidentiality obligations and may be disciplined or terminated
                if they fail to meet these obligations.
              </p>
              <p>
                The insights we gain from maintaining our services help us
                detect and automatically block security threats from ever
                reaching you.
              </p>
              <p>
                However, these measures are unable to provide absolute
                assurance. Therefore, although FR8 takes great efforts to
                protect your personal information, FR8 cannot guarantee and you
                cannot reasonably expect that FR8’s databases will be immune
                from any wrongdoings, malfunctions, unlawful interceptions or
                access, or other kinds of abuse and misuse.
              </p>
              <h2>Compliance & cooperation with regulators</h2>
              <p>
                We regularly review this Privacy Policy and make sure that we
                process your information in ways that comply with it.
              </p>
              <h3>Data transfers</h3>
              <p>
                We store data on servers located around the world and your
                information may be processed on servers located outside of the
                country where you live. Data protection laws vary among
                countries, with some providing more protection than others.
                Regardless of where your information is processed, we apply the
                same protections described in this policy.
              </p>
              <p>
                When we receive formal written complaints, we respond by
                contacting the person who made the complaint. We work with the
                appropriate regulatory authorities, including local data
                protection authorities, to resolve any complaints regarding the
                transfer of your data that we cannot resolve with you directly.
              </p>
              <h3>European requirements</h3>
              <p>
                If European Union (EU) or United Kingdom (UK) data protection
                law applies to the processing of your information, we provide
                the controls described in this policy so you can exercise your
                right to request access to, update, remove, delete, and restrict
                the processing of your information.
              </p>
              <p>
                You can also export a copy of data in your FR8 account if you
                want to back it up or export your information to another
                service. You can log in to the dashboard by going to the FR8
                website, then Settings, then choose Download your data archive.
                Note that in order to access the dashboard you will need a FR8
                account with a valid email address to receive your data archive.
              </p>
              <p>
                You also have the right to object to the processing of your
                information.
              </p>
              <p>
                We process your information for the purposes described in this
                policy, based on the following legal grounds:
              </p>
              <p>With your consent</p>
              <p>
                We ask for your agreement to process your information for
                specific purposes and you have the right to withdraw your
                consent at any time. You can manage your settings at any time,
                including your in-app Privacy Settings.
              </p>
              <p>When we’re pursuing legitimate interests</p>
              <p>
                We process your information for our legitimate interests and
                those of third parties (such as partners including advertisers,
                in order to report use statistics) while applying appropriate
                safeguards that protect your privacy. This means that we process
                your information for things like:
              </p>
              <ul>
                <li>
                  Providing, maintaining, and improving our services to meet the
                  needs of our users
                </li>
                <li>
                  Developing new services and features that are useful for our
                  users
                </li>
                <li>
                  Understanding how people use our services (including how they
                  interact with our ads) to ensure and improve the performance
                  of our services
                </li>
                <li>
                  Customizing our services to provide you with a better user
                  experience
                </li>
                <li>Marketing to inform users about our services</li>
                <li>
                  Providing advertising, which keeps many of our services free
                </li>
                <li>
                  Detecting, preventing, or otherwise addressing fraud, abuse,
                  security, or technical issues with our services
                </li>
                <li>
                  Protecting against harm to the rights, property or safety of
                  FR8, our users, or the public as required or permitted by law,
                  including disclosing information to government authorities
                </li>
                <li>
                  Performing research that improves our services for our users
                  and benefits the public
                </li>
                <li>
                  Fulfilling obligations to our partners like developers and
                  rights holders
                </li>
                <li>
                  Enforcing legal claims, including investigation of potential
                  violations of applicable Terms of Service
                </li>
              </ul>
              <p>When we’re providing a service</p>
              <p>
                We process your data to provide a service you’ve asked for under
                a contract (including our terms of use).
              </p>
              <p>When we’re complying with legal obligations</p>
              <p>
                We’ll process your data when we have a legal obligation to do
                so, for example, if we’re responding to legal process or an
                enforceable governmental request.
              </p>
              <p>
                If you have questions, you can contact FR8 and our data
                protection office at: support@fr8.ai. And you can contact your
                local data protection authority if you have concerns regarding
                your rights under local law.
              </p>
              <h2>Brazilian requirements</h2>
              <p>
                If Brazilian data protection law applies to the processing of
                your information, we provide the controls described in this
                policy so you can exercise your right to:
              </p>
              <ul>
                <li>
                  Obtain confirmation on whether we process your information
                </li>
                <li>
                  Request access to, update, review, anonymise, and remove your
                  information
                </li>
                <li>
                  Object to or restrict the processing of your information
                </li>
                <li>Export your information to another service</li>
              </ul>
              <p>
                We process your information for the purposes described in this
                policy, based on the following legal grounds:
              </p>
              <h4>With your consent</h4>
              <p>
                Where we ask for your consent to process your information for
                specific purposes, you do not have to provide your consent but
                where you choose to do so, you have the right to withdraw your
                consent at any time. You can manage your settings at any time,
                including your in-app Privacy Settings. You also have the right
                to obtain information about the effects of not providing your
                consent to processing for specific purposes.
              </p>
              <h4>When we’re pursuing legitimate interests</h4>
              <p>
                We process your information for our legitimate interests and
                those of third parties (such as partners including advertisers,
                in order to report use statistics) while applying appropriate
                safeguards that protect your privacy. This means that we process
                your information for things like:
              </p>
              <ul>
                <li>
                  {" "}
                  Providing, maintaining, and improving our services to meet the
                  needs of our users
                </li>
                <li>
                  Developing new services and features that are useful for our
                  users
                </li>
                <li>
                  {" "}
                  Understanding how people use our services (including how they
                  interact with our ads) to ensure and improve the performance
                  of our services
                </li>
                <li>
                  Customizing our services to provide you with a better user
                  experience
                </li>
                <li>Marketing to inform users about our services</li>
                <li>
                  Providing advertising, which keeps many of our services free
                </li>
                <li>
                  Detecting, preventing, or otherwise addressing fraud, abuse,
                  security, or technical issues with our services
                </li>
                <li>
                  {" "}
                  Protecting against harm to the rights, property or safety of
                  FR8, our users, or the public as required or permitted by law,
                  including disclosing information to government authorities
                </li>
                <li>
                  Performing research that improves our services for our users
                  and benefits the public
                </li>
                <li>
                  Fulfilling obligations to our partners like developers and
                  rights holders
                </li>
                <li>
                  {" "}
                  Enforcing legal claims, including investigation of potential
                  violations of applicable Terms of Service
                </li>
              </ul>
              <p>When we’re providing a service</p>
              <p>
                We process your data to provide a service you’ve asked for under
                a contract (including our terms of use).
              </p>
              <p>When we’re complying with legal obligations</p>
              <p>
                We’ll process your data when we have a legal obligation to do
                so, for example, if we’re responding to legal process or an
                enforceable governmental request. If you have questions, you can
                contact FR8 and our data protection office at: support@fr8.ai.
                And you can contact your local data protection authority if you
                have concerns regarding your rights under Brazilian law.
              </p>
              <h3>California requirement</h3>
              <p>
                The California Consumer Privacy Act (CCPA) requires specific
                disclosures for California residents. This Privacy Policy is
                designed to help you understand how FR8 handles your
                information:
              </p>
              <p>
                We explain the categories of information FR8 collects and the
                sources of that information in Information That is being
                collected.
              </p>
              <p>
                We explain how FR8 uses information in Why FR8 collects data.
              </p>
              <p>
                We explain when FR8 may share information in Sharing your
                information. FR8 does not sell your personal information.
              </p>
              <p>
                The CCPA also provides the right to request information about
                how FR8 collects, uses, and discloses your personal information.
                And it gives you the right to access your information and
                request that FR8 delete that information. Finally, the CCPA
                provides the right to not be discriminated against for
                exercising your privacy rights
              </p>
              <p>
                We describe the choices you have to manage your privacy and data
                in Controlling your personal information section. You can
                exercise your rights by using these controls, which allow you to
                access, review, update and delete your information, as well as
                export and download a copy of it. You can log in to the
                dashboard by going to the FR8 website, then Settings, then
                choose Download your data archive. Note that in order to access
                the dashboard you will need a FR8 account with a valid email
                address to receive your data archive. If you have questions or
                requests related to your rights under the CCPA, you (or your
                authorized agent) can also contact FR8 at support@fr8.ai.
              </p>
              <p>
                The CCPA requires a description of data practices using specific
                categories. This table uses these categories to organize the
                information in this Privacy Policy.
              </p>
              <h2>Changes to this Privacy Policy</h2>
              <p>
                FR8 may from time to time change the terms of this Privacy
                Policy. Substantial changes will take effect 30 days after FR8
                has posted a:
              </p>
              <ul>
                <li>
                  System message to users notifying them of changes to the
                  Privacy Policy; and
                </li>
                <li>
                  Notification on the Website’s homepage or any other relevant
                  web pages, explaining the changes to the Privacy Policy
                  alongside a comparison of the “old” and “new” versions of the
                  Privacy Policy.
                </li>
              </ul>
              <p>
                Other changes will take effect 7 days after their initial
                posting on the Website. However, if FR8 amends this Privacy
                Policy to comply with legal requirements, the amendments will
                become effective immediately upon their initial posting, or as
                required.
              </p>
              <p>
                You agree to be bound by any of the changes made in the terms of
                this Privacy Policy. Continuing to use the Services will
                indicate your acceptance of the amended terms. If you do not
                agree with any of the amended terms, you must avoid any further
                use of the Services.
              </p>
              <h3>Last modified: 9 September 2020</h3>
              <h3>
                The Company has registered a database with the Israeli Database
                Registrar
              </h3>
            </ul>
          </div>
        </div>
      </div>
    </Layout>
  );
}
